package somaApp;


/**
* somaApp/somaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from soma.idl
* Terça-feira, 19 de Junho de 2018 22h16min51s GFT
*/

abstract public class somaHelper
{
  private static String  _id = "IDL:somaApp/soma:1.0";

  public static void insert (org.omg.CORBA.Any a, somaApp.soma that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static somaApp.soma extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (somaApp.somaHelper.id (), "soma");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static somaApp.soma read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_somaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, somaApp.soma value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static somaApp.soma narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof somaApp.soma)
      return (somaApp.soma)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      somaApp._somaStub stub = new somaApp._somaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static somaApp.soma unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof somaApp.soma)
      return (somaApp.soma)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      somaApp._somaStub stub = new somaApp._somaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
