package somaApp;


/**
* somaApp/somaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from soma.idl
* Terça-feira, 19 de Junho de 2018 22h16min51s GFT
*/

public interface somaOperations 
{
  int somar (int numero1, int numero2);
  void shutdown ();
} // interface somaOperations
