package somaApp;


/**
* somaApp/soma.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from soma.idl
* Terça-feira, 19 de Junho de 2018 22h16min51s GFT
*/

public interface soma extends somaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface soma
