package somaApp;


/**
* somaApp/somaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from soma.idl
* Terça-feira, 19 de Junho de 2018 22h16min51s GFT
*/

public abstract class somaPOA extends org.omg.PortableServer.Servant
 implements somaApp.somaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("somar", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // somaApp/soma/somar
       {
         int numero1 = in.read_long ();
         int numero2 = in.read_long ();
         int $result = (int)0;
         $result = this.somar (numero1, numero2);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // somaApp/soma/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:somaApp/soma:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public soma _this() 
  {
    return somaHelper.narrow(
    super._this_object());
  }

  public soma _this(org.omg.CORBA.ORB orb) 
  {
    return somaHelper.narrow(
    super._this_object(orb));
  }


} // class somaPOA
